# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [14]:
# Import torch

import torch

# Create random tensor

ten = torch.rand(7,7)
ten

tensor([[0.7703, 0.0178, 0.8119, 0.1087, 0.3943, 0.2973, 0.4037],
        [0.4018, 0.0513, 0.0683, 0.4218, 0.5065, 0.2729, 0.6883],
        [0.0500, 0.4663, 0.9397, 0.2961, 0.9515, 0.6811, 0.0488],
        [0.8163, 0.4423, 0.2768, 0.8998, 0.0960, 0.5537, 0.3953],
        [0.8571, 0.6396, 0.7403, 0.6766, 0.3798, 0.3948, 0.0880],
        [0.7709, 0.8970, 0.8421, 0.1473, 0.5223, 0.1475, 0.2248],
        [0.2086, 0.6709, 0.2020, 0.4891, 0.5210, 0.8223, 0.1220]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
ten2 = torch.rand(1,7)
ten_tot = torch.matmul(ten,ten2.T)

ten_tot

# Perform matrix multiplication


tensor([[1.9130],
        [1.7526],
        [1.7672],
        [1.5551],
        [1.9772],
        [1.2098],
        [1.1166]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [35]:
import torch

# Create random tensor

RANDOM_SEED = 0

torch.manual_seed(RANDOM_SEED)
ten = torch.rand(7,7)


ten2 = torch.rand(1,7)


ten_tot = torch.matmul(ten,ten2.T)

ten_tot


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [36]:
# Set random seed on the GPU

torch.manual_seed(1234)




### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [39]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU

device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
ten1 = torch.rand(2,3).to(device)

ten2 = torch.rand(2,3).to(device)

device, ten1, ten2


('cpu',
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max

# Find min


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max


# Find arg min



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed


# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes
